// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: pkg/proto/scheduler.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Resource represents CPU, memory, and disk
type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           int64                  `protobuf:"varint,1,opt,name=cpu,proto3" json:"cpu,omitempty"`       // millicores
	Memory        int64                  `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"` // MB
	Disk          int64                  `protobuf:"varint,3,opt,name=disk,proto3" json:"disk,omitempty"`     // MB
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_pkg_proto_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_pkg_proto_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *Resource) GetCpu() int64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *Resource) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Resource) GetDisk() int64 {
	if x != nil {
		return x.Disk
	}
	return 0
}

// NodeInfo - Worker sends this to register with Master
type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Total         *Resource              `protobuf:"bytes,3,opt,name=total,proto3" json:"total,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"` // Worker's IP:Port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_pkg_proto_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeInfo) GetTotal() *Resource {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// RegisterResponse - Master responds with registration status
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_pkg_proto_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// HeartbeatRequest - Worker sends periodically to report status
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Available     *Resource              `protobuf:"bytes,2,opt,name=available,proto3" json:"available,omitempty"`
	RunningTasks  []string               `protobuf:"bytes,3,rep,name=running_tasks,json=runningTasks,proto3" json:"running_tasks,omitempty"`
	Healthy       bool                   `protobuf:"varint,4,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_pkg_proto_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetAvailable() *Resource {
	if x != nil {
		return x.Available
	}
	return nil
}

func (x *HeartbeatRequest) GetRunningTasks() []string {
	if x != nil {
		return x.RunningTasks
	}
	return nil
}

func (x *HeartbeatRequest) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

// HeartbeatResponse - Master acknowledges heartbeat
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_pkg_proto_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Task - A unit of work
type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Required      *Resource              `protobuf:"bytes,3,opt,name=required,proto3" json:"required,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                         // "pending", "running", "completed", "failed"
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_pkg_proto_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_pkg_proto_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetRequired() *Resource {
	if x != nil {
		return x.Required
	}
	return nil
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// GetTaskRequest - Worker asks Master for tasks
type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_pkg_proto_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *GetTaskRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// TaskStatusRequest - Worker reports task completion
type TaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusRequest) Reset() {
	*x = TaskStatusRequest{}
	mi := &file_pkg_proto_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusRequest) ProtoMessage() {}

func (x *TaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusRequest.ProtoReflect.Descriptor instead.
func (*TaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *TaskStatusRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TaskStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskStatusRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// TaskStatusResponse - Master acknowledges task status
type TaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusResponse) Reset() {
	*x = TaskStatusResponse{}
	mi := &file_pkg_proto_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusResponse) ProtoMessage() {}

func (x *TaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusResponse.ProtoReflect.Descriptor instead.
func (*TaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_scheduler_proto_rawDescGZIP(), []int{8}
}

func (x *TaskStatusResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *TaskStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// AssignTaskRequest - Master tells Worker to run a task
type AssignTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignTaskResponse) Reset() {
	*x = AssignTaskResponse{}
	mi := &file_pkg_proto_scheduler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignTaskResponse) ProtoMessage() {}

func (x *AssignTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_scheduler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignTaskResponse.ProtoReflect.Descriptor instead.
func (*AssignTaskResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_scheduler_proto_rawDescGZIP(), []int{9}
}

func (x *AssignTaskResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *AssignTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// StatusRequest - Get worker status
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_pkg_proto_scheduler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_scheduler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_scheduler_proto_rawDescGZIP(), []int{10}
}

func (x *StatusRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// WorkerStatusResponse - Worker reports its current status
type WorkerStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Available     *Resource              `protobuf:"bytes,3,opt,name=available,proto3" json:"available,omitempty"`
	Total         *Resource              `protobuf:"bytes,4,opt,name=total,proto3" json:"total,omitempty"`
	RunningTasks  []string               `protobuf:"bytes,5,rep,name=running_tasks,json=runningTasks,proto3" json:"running_tasks,omitempty"`
	Healthy       bool                   `protobuf:"varint,6,opt,name=healthy,proto3" json:"healthy,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,7,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerStatusResponse) Reset() {
	*x = WorkerStatusResponse{}
	mi := &file_pkg_proto_scheduler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStatusResponse) ProtoMessage() {}

func (x *WorkerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_scheduler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStatusResponse.ProtoReflect.Descriptor instead.
func (*WorkerStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_scheduler_proto_rawDescGZIP(), []int{11}
}

func (x *WorkerStatusResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *WorkerStatusResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkerStatusResponse) GetAvailable() *Resource {
	if x != nil {
		return x.Available
	}
	return nil
}

func (x *WorkerStatusResponse) GetTotal() *Resource {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *WorkerStatusResponse) GetRunningTasks() []string {
	if x != nil {
		return x.RunningTasks
	}
	return nil
}

func (x *WorkerStatusResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *WorkerStatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

// SchedulingResult - Result of scheduling decision
type SchedulingResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Score         float64                `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedulingResult) Reset() {
	*x = SchedulingResult{}
	mi := &file_pkg_proto_scheduler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulingResult) ProtoMessage() {}

func (x *SchedulingResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_scheduler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulingResult.ProtoReflect.Descriptor instead.
func (*SchedulingResult) Descriptor() ([]byte, []int) {
	return file_pkg_proto_scheduler_proto_rawDescGZIP(), []int{12}
}

func (x *SchedulingResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SchedulingResult) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SchedulingResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SchedulingResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SchedulingResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

// Empty - For endpoints that don't need parameters
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_proto_scheduler_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_scheduler_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_proto_scheduler_proto_rawDescGZIP(), []int{13}
}

var File_pkg_proto_scheduler_proto protoreflect.FileDescriptor

const file_pkg_proto_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/proto/scheduler.proto\x12\tscheduler\"H\n" +
	"\bResource\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\x03R\x03cpu\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\x03R\x06memory\x12\x12\n" +
	"\x04disk\x18\x03 \x01(\x03R\x04disk\"s\n" +
	"\bNodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x05total\x18\x03 \x01(\v2\x13.scheduler.ResourceR\x05total\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\"_\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\"\x9d\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x121\n" +
	"\tavailable\x18\x02 \x01(\v2\x13.scheduler.ResourceR\tavailable\x12#\n" +
	"\rrunning_tasks\x18\x03 \x03(\tR\frunningTasks\x12\x18\n" +
	"\ahealthy\x18\x04 \x01(\bR\ahealthy\"I\n" +
	"\x11HeartbeatResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x92\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\brequired\x18\x03 \x01(\v2\x13.scheduler.ResourceR\brequired\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"w\n" +
	"\x11TaskStatusRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"J\n" +
	"\x12TaskStatusResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"J\n" +
	"\x12AssignTaskResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"(\n" +
	"\rStatusRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\x87\x02\n" +
	"\x14WorkerStatusResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x121\n" +
	"\tavailable\x18\x03 \x01(\v2\x13.scheduler.ResourceR\tavailable\x12)\n" +
	"\x05total\x18\x04 \x01(\v2\x13.scheduler.ResourceR\x05total\x12#\n" +
	"\rrunning_tasks\x18\x05 \x03(\tR\frunningTasks\x12\x18\n" +
	"\ahealthy\x18\x06 \x01(\bR\ahealthy\x12%\n" +
	"\x0euptime_seconds\x18\a \x01(\x03R\ruptimeSeconds\"\x8c\x01\n" +
	"\x10SchedulingResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\"\a\n" +
	"\x05Empty2\x9a\x02\n" +
	"\x06Master\x12@\n" +
	"\fRegisterNode\x12\x13.scheduler.NodeInfo\x1a\x1b.scheduler.RegisterResponse\x12F\n" +
	"\tHeartbeat\x12\x1b.scheduler.HeartbeatRequest\x1a\x1c.scheduler.HeartbeatResponse\x125\n" +
	"\aGetTask\x12\x19.scheduler.GetTaskRequest\x1a\x0f.scheduler.Task\x12O\n" +
	"\x10ReportTaskStatus\x12\x1c.scheduler.TaskStatusRequest\x1a\x1d.scheduler.TaskStatusResponse2\x94\x01\n" +
	"\x06Worker\x12<\n" +
	"\n" +
	"AssignTask\x12\x0f.scheduler.Task\x1a\x1d.scheduler.AssignTaskResponse\x12L\n" +
	"\x0fGetWorkerStatus\x12\x18.scheduler.StatusRequest\x1a\x1f.scheduler.WorkerStatusResponseB\vZ\tpkg/protob\x06proto3"

var (
	file_pkg_proto_scheduler_proto_rawDescOnce sync.Once
	file_pkg_proto_scheduler_proto_rawDescData []byte
)

func file_pkg_proto_scheduler_proto_rawDescGZIP() []byte {
	file_pkg_proto_scheduler_proto_rawDescOnce.Do(func() {
		file_pkg_proto_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_scheduler_proto_rawDesc), len(file_pkg_proto_scheduler_proto_rawDesc)))
	})
	return file_pkg_proto_scheduler_proto_rawDescData
}

var file_pkg_proto_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pkg_proto_scheduler_proto_goTypes = []any{
	(*Resource)(nil),             // 0: scheduler.Resource
	(*NodeInfo)(nil),             // 1: scheduler.NodeInfo
	(*RegisterResponse)(nil),     // 2: scheduler.RegisterResponse
	(*HeartbeatRequest)(nil),     // 3: scheduler.HeartbeatRequest
	(*HeartbeatResponse)(nil),    // 4: scheduler.HeartbeatResponse
	(*Task)(nil),                 // 5: scheduler.Task
	(*GetTaskRequest)(nil),       // 6: scheduler.GetTaskRequest
	(*TaskStatusRequest)(nil),    // 7: scheduler.TaskStatusRequest
	(*TaskStatusResponse)(nil),   // 8: scheduler.TaskStatusResponse
	(*AssignTaskResponse)(nil),   // 9: scheduler.AssignTaskResponse
	(*StatusRequest)(nil),        // 10: scheduler.StatusRequest
	(*WorkerStatusResponse)(nil), // 11: scheduler.WorkerStatusResponse
	(*SchedulingResult)(nil),     // 12: scheduler.SchedulingResult
	(*Empty)(nil),                // 13: scheduler.Empty
}
var file_pkg_proto_scheduler_proto_depIdxs = []int32{
	0,  // 0: scheduler.NodeInfo.total:type_name -> scheduler.Resource
	0,  // 1: scheduler.HeartbeatRequest.available:type_name -> scheduler.Resource
	0,  // 2: scheduler.Task.required:type_name -> scheduler.Resource
	0,  // 3: scheduler.WorkerStatusResponse.available:type_name -> scheduler.Resource
	0,  // 4: scheduler.WorkerStatusResponse.total:type_name -> scheduler.Resource
	1,  // 5: scheduler.Master.RegisterNode:input_type -> scheduler.NodeInfo
	3,  // 6: scheduler.Master.Heartbeat:input_type -> scheduler.HeartbeatRequest
	6,  // 7: scheduler.Master.GetTask:input_type -> scheduler.GetTaskRequest
	7,  // 8: scheduler.Master.ReportTaskStatus:input_type -> scheduler.TaskStatusRequest
	5,  // 9: scheduler.Worker.AssignTask:input_type -> scheduler.Task
	10, // 10: scheduler.Worker.GetWorkerStatus:input_type -> scheduler.StatusRequest
	2,  // 11: scheduler.Master.RegisterNode:output_type -> scheduler.RegisterResponse
	4,  // 12: scheduler.Master.Heartbeat:output_type -> scheduler.HeartbeatResponse
	5,  // 13: scheduler.Master.GetTask:output_type -> scheduler.Task
	8,  // 14: scheduler.Master.ReportTaskStatus:output_type -> scheduler.TaskStatusResponse
	9,  // 15: scheduler.Worker.AssignTask:output_type -> scheduler.AssignTaskResponse
	11, // 16: scheduler.Worker.GetWorkerStatus:output_type -> scheduler.WorkerStatusResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_proto_scheduler_proto_init() }
func file_pkg_proto_scheduler_proto_init() {
	if File_pkg_proto_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_scheduler_proto_rawDesc), len(file_pkg_proto_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_proto_scheduler_proto_goTypes,
		DependencyIndexes: file_pkg_proto_scheduler_proto_depIdxs,
		MessageInfos:      file_pkg_proto_scheduler_proto_msgTypes,
	}.Build()
	File_pkg_proto_scheduler_proto = out.File
	file_pkg_proto_scheduler_proto_goTypes = nil
	file_pkg_proto_scheduler_proto_depIdxs = nil
}
